[package]
name = "leptos-use"
version = "0.1.9"
edition = "2021"
authors = ["Marc-Stefan Cassola"]
categories = ["gui", "web-programming"]
description = "Collection of essential Leptos utilities inspired by SolidJS USE / VueUse"
exclude = ["examples/", "tests/"]
keywords = ["leptos", "utilities"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/Synphonyte/leptos-use"
homepage = "https://leptos-use.rs"


[dependencies]
leptos = "0.3.0"
wasm-bindgen = "0.2.86"
js-sys = "0.3.63"
default-struct-builder = { path = "../default-struct-builder" }
num = { version = "0.4.0", optional = true }
serde = { version = "1.0.163", optional = true }
serde_json = { version = "1.0.96", optional = true }
paste = { version = "1.0.12", optional = true }

[dependencies.web-sys]
version = "0.3.63"
features = [
    "CssStyleDeclaration",
    "CustomEvent",
    "CustomEventInit",
    "DomRectReadOnly",
    "Element",
    "MediaQueryList",
    "MouseEvent",
    "Navigator",
    "ResizeObserver",
    "ResizeObserverBoxOptions",
    "ResizeObserverEntry",
    "ResizeObserverOptions",
    "ResizeObserverSize",
    "ScrollBehavior",
    "ScrollToOptions",
    "Touch",
    "TouchEvent",
    "TouchList",
    "Window",
]

[features]
docs = []
math = ["num", "paste"]
storage = ["serde", "serde_json", "web-sys/Storage", "web-sys/StorageEvent"]

[package.metadata."docs.rs"]
all-features = true
rustdoc-args = ["--cfg=web_sys_unstable_apis"]
rustc-args = ["--cfg=web_sys_unstable_apis"]