[package]
name = "leptos-use"
version = "0.1.6"
edition = "2021"
authors = ["Marc-Stefan Cassola"]
categories = ["gui", "web-programming"]
description = "Collection of essential Leptos utilities inspired by SolidJS USE / VueUse"
exclude = ["examples/", "tests/"]
keywords = ["leptos", "utilities"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/Synphonyte/leptos-use"


[dependencies]
leptos = "0.3.0"
wasm-bindgen = "0.2.86"
js-sys = "0.3.63"
default-struct-builder = "0.2.0"
num = { version = "0.4.0", optional = true }

[dependencies.web-sys]
version = "0.3.63"
features = [
    "CssStyleDeclaration",
    "DomRectReadOnly",
    "MouseEvent",
    "Navigator",
    "ResizeObserver",
    "ResizeObserverBoxOptions",
    "ResizeObserverEntry",
    "ResizeObserverOptions",
    "ResizeObserverSize",
    "ScrollBehavior",
    "ScrollToOptions",
    "Touch",
    "TouchEvent",
    "TouchList",
]

[features]
docs = []
math = ["num"]

[package.metadata."docs.rs"]
all-features = true
