[book]
authors = ["Marc-Stefan Cassola"]
language = "en"
multilingual = false
src = "src"
title = "Leptos-Use Documentation"

[output.html]
no-section-label = true
additional-css = ["custom.css"]
additional-js = ["demo-iframe.js"]

[preprocessor.cmdrun]