on:
  pull_request:
  workflow_dispatch:

name: Tests

permissions: write-all

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
          components: rustfmt, clippy, rust-src
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Check formatting
        run: cargo fmt --check
# TODO: this action doesn't seem to work
#      - name: Clippy check
#        uses: auguwu/clippy-action@1.1.2
#        with:
#          args: --all-features --tests
#          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run tests
        run: cargo test --all-features
